"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import Link from "next/link";
import { DEFAULT_THEME, pageSchema, snapshotSchema, themeSchema, type SitePage, type SiteTheme } from "@/modules/omnisite/model";
import { SiteView } from "@/modules/omnisite/SiteView";

type Team = { id: string; name: string };
type Template = { id: string; name: string; layout_key: "classic"|"bold"|"minimal"; starter_pages: SitePage[]; default_theme: SiteTheme };
type Site = { id: string; team_id: string; slug: string; site_name: string; layout_key: "classic"|"bold"|"minimal";
  theme: SiteTheme; logo_path: string|null; published_version: number|null };
type PageRow = { id: string; slug: string; title: string; seo_description: string; nav_order: number; visible: boolean; sections: SitePage["sections"] };
export default function OmniSiteEditor() {
 const client=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [teams,setTeams]=useState<Team[]>([]),[teamId,setTeamId]=useState(""),[templates,setTemplates]=useState<Template[]>([]);
 const [site,setSite]=useState<Site|null>(null),[pages,setPages]=useState<PageRow[]>([]),[selectedPage,setSelectedPage]=useState("");
 const [templateId,setTemplateId]=useState(""),[newSlug,setNewSlug]=useState(""),[newName,setNewName]=useState("");
 const [message,setMessage]=useState("Sign in to manage your team website."),[preview,setPreview]=useState(false),[uploading,setUploading]=useState(false);
 const load=useCallback(async(id:string)=>{if(!client)return;const s=await client.from("team_sites").select("*").eq("team_id",id).maybeSingle();if(s.error){setMessage(s.error.message);return}setSite(s.data as Site|null);if(s.data){const p=await client.from("site_pages").select("*").eq("team_id",id).eq("site_id",s.data.id).order("nav_order");if(p.error){setMessage(p.error.message);return}setPages((p.data??[]) as PageRow[]);setSelectedPage((old)=>old||p.data?.[0]?.id||"")}else setPages([]);},[client]);
 useEffect(()=>{async function init(){if(!client)return;const a=await client.auth.getUser();if(!a.data.user){setMessage("Sign in with your team account before opening OmniSite.");return}const m=await client.from("team_memberships").select("id,team_id,role,status").eq("user_id",a.data.user.id).eq("status","ACTIVE");if(m.error){setMessage(m.error.message);return}const possible=(m.data??[]).filter(x=>x.role==="OWNER").map(x=>x.team_id);
 const other=(m.data??[]).filter(x=>x.role!=="OWNER");for(const row of other){const q=await client.from("team_member_module_permissions").select("access_level").eq("team_id",row.team_id).eq("membership_id",row.id).eq("module_key","omnisite").eq("access_level","MANAGE").maybeSingle();if(q.data)possible.push(row.team_id)}
 const ids=[...new Set(possible)];if(!ids.length){setMessage("No team has granted you OmniSite management access.");return}const t=await client.from("teams").select("id,name").in("id",ids);if(t.error){setMessage(t.error.message);return}setTeams((t.data??[]) as Team[]);setTeamId(ids[0]);const list=await client.from("site_templates").select("id,name,layout_key,starter_pages,default_theme").eq("status","PUBLISHED");if(list.error){setMessage(list.error.message);return}setTemplates((list.data??[]) as Template[]);setTemplateId(list.data?.[0]?.id||"");setMessage("")};void init()},[client]);
 useEffect(()=>{if(teamId)void load(teamId)},[teamId,load]);
 const current=pages.find(p=>p.id===selectedPage);
 async function createSite(){if(!client||!teamId||!templateId)return;const r=await client.rpc("create_team_site",{target_team_id:teamId,selected_template_id:templateId,requested_slug:newSlug.trim().toLowerCase(),requested_name:newName.trim()});setMessage(r.error?.message||"Website created. Edit and publish it when ready.");if(!r.error)await load(teamId)}
 async function saveSite(){if(!client||!site)return;const valid=themeSchema.safeParse(site.theme);if(!valid.success){setMessage("Choose valid six-digit colors.");return}const r=await client.from("team_sites").update({site_name:site.site_name,theme:valid.data,logo_path:site.logo_path,updated_at:new Date().toISOString()}).eq("team_id",teamId).eq("id",site.id);setMessage(r.error?.message||"Branding saved as a draft.")}
 async function savePage(){if(!client||!site||!current)return;const valid=pageSchema.safeParse({slug:current.slug,title:current.title,seoDescription:current.seo_description,navOrder:current.nav_order,visible:current.visible,sections:current.sections});if(!valid.success){setMessage("Page content is invalid. Check section type, length, and links.");return}const r=await client.from("site_pages").update({title:valid.data.title,seo_description:valid.data.seoDescription,nav_order:valid.data.navOrder,visible:valid.data.visible,sections:valid.data.sections,updated_at:new Date().toISOString()}).eq("team_id",teamId).eq("site_id",site.id).eq("id",current.id);setMessage(r.error?.message||"Page saved as a draft.");if(!r.error)await load(teamId)}
 async function uploadLogo(file:File){if(!client||!site)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>2097152){setMessage("Use a PNG, JPEG, or WebP logo under 2 MB.");return}setUploading(true);try{const image=await createImageBitmap(file);if(image.width>3000||image.height>3000||image.width<64||image.height<64){setMessage("Logo dimensions must be 64–3000 pixels.");return}const ext=file.type==="image/png"?"png":file.type==="image/jpeg"?"jpg":"webp";const path=`${teamId}/${crypto.randomUUID()}.${ext}`;const up=await client.storage.from("omnisite-assets").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(up.error.message);return}const meta=await client.from("site_assets").insert({team_id:teamId,site_id:site.id,object_path:path,mime_type:file.type,bytes:file.size});if(meta.error){await client.storage.from("omnisite-assets").remove([path]);setMessage(meta.error.message);return}setSite({...site,logo_path:path});setMessage("Logo uploaded. Save branding to use it on the site.")}finally{setUploading(false)}}
 async function publish(){if(!client||!site)return;const r=await client.rpc("publish_team_site",{target_team_id:teamId,target_site_id:site.id});setMessage(r.error?.message||`Published version ${r.data}.`);if(!r.error)await load(teamId)}
 async function rollback(){if(!client||!site||!site.published_version||site.published_version<2)return;const r=await client.rpc("rollback_team_site",{target_team_id:teamId,target_site_id:site.id,source_version:site.published_version-1});setMessage(r.error?.message||`Restored previous publication as version ${r.data}.`);if(!r.error)await load(teamId)}
 function addSection(type:"hero"|"richText"|"cta"|"cards"){
  if(!current)return;
  const section=type==="hero"?{type,heading:"New headline",text:"Add a short introduction."}:
    type==="richText"?{type,heading:"New section",text:"Add your text."}:
    type==="cta"?{type,heading:"Join us",label:"Get in touch",href:"/contact"}:
    {type,heading:"Highlights",items:[{title:"Highlight",text:"Describe it."}]};
  setPages(pages.map(p=>p.id===current.id?{...p,sections:[...p.sections,section] as SitePage["sections"]}:p));
 }
 function moveSection(index:number,by:number){if(!current)return;const sections=[...current.sections];const target=index+by;if(target<0||target>=sections.length)return;[sections[index],sections[target]]=[sections[target],sections[index]];setPages(pages.map(p=>p.id===current.id?{...p,sections}:p))}
 function removeSection(index:number){if(!current)return;setPages(pages.map(p=>p.id===current.id?{...p,sections:p.sections.filter((_,i)=>i!==index)}:p))}
 const draft=site?snapshotSchema.safeParse({teamId,siteId:site.id,slug:site.slug,siteName:site.site_name,layout:site.layout_key,theme:site.theme||DEFAULT_THEME,logoPath:site.logo_path,pages:pages.map(p=>({slug:p.slug,title:p.title,seoDescription:p.seo_description,navOrder:p.nav_order,visible:p.visible,sections:p.sections}))}):null;
 return <main className="os-editor"><Link href="/">← OmniTeam</Link><h1>OmniSite</h1><p role="status">{message}</p>{teams.length>0&&<label>Team <select value={teamId} onChange={e=>{setTeamId(e.target.value);setSelectedPage("")}}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 {!site&&teams.length>0&&<section><h2>Start a team website</h2><label>Template <select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Site name <input value={newName} onChange={e=>setNewName(e.target.value)} /></label><label>Public slug <input value={newSlug} onChange={e=>setNewSlug(e.target.value)} placeholder="your-team" /></label><button onClick={createSite}>Create draft</button></section>}
 {site&&<><section><h2>Branding</h2><label>Site name <input value={site.site_name} onChange={e=>setSite({...site,site_name:e.target.value})}/></label>{(["primary","secondary","accent"] as const).map(k=><label key={k}>{k} <input type="color" value={site.theme[k]} onChange={e=>setSite({...site,theme:{...site.theme,[k]:e.target.value}})}/></label>)}<label>Surface <select value={site.theme.surface} onChange={e=>setSite({...site,theme:{...site.theme,surface:e.target.value as "light"|"dark"}})}><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Team logo <input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadLogo(file)}}/></label><button onClick={saveSite}>Save branding</button></section>
 <section><h2>Pages</h2><label>Page <select value={selectedPage} onChange={e=>setSelectedPage(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{current&&<><label>Title <input value={current.title} onChange={e=>setPages(pages.map(p=>p.id===current.id?{...p,title:e.target.value}:p))}/></label><label>SEO description <input value={current.seo_description} onChange={e=>setPages(pages.map(p=>p.id===current.id?{...p,seo_description:e.target.value}:p))}/></label><label><input type="checkbox" checked={current.visible} onChange={e=>setPages(pages.map(p=>p.id===current.id?{...p,visible:e.target.checked}:p))}/> Visible when published</label><h3>Sections</h3>{current.sections.map((section,i)=><div className="os-section-editor" key={i}><b>{section.type}</b>{Object.entries(section).filter(([key])=>key!=="type"&&key!=="items").map(([key,val])=><label key={key}>{key}<textarea value={String(val)} onChange={e=>{const sections=[...current.sections];sections[i]={...section,[key]:e.target.value} as typeof section;setPages(pages.map(p=>p.id===current.id?{...p,sections}:p))}}/></label>)}{section.type==="cards"&&section.items.map((item,itemIndex)=><div key={itemIndex}><label>Card title<input value={item.title} onChange={e=>{const sections=[...current.sections];const cards={...section,items:section.items.map((entry,n)=>n===itemIndex?{...entry,title:e.target.value}:entry)};sections[i]=cards;setPages(pages.map(p=>p.id===current.id?{...p,sections}:p))}}/></label><label>Card text<textarea value={item.text} onChange={e=>{const sections=[...current.sections];sections[i]={...section,items:section.items.map((entry,n)=>n===itemIndex?{...entry,text:e.target.value}:entry)};setPages(pages.map(p=>p.id===current.id?{...p,sections}:p))}}/></label></div>)}<div><button onClick={()=>moveSection(i,-1)}>Move up</button><button onClick={()=>moveSection(i,1)}>Move down</button><button onClick={()=>removeSection(i)}>Remove section</button></div></div>)}<div><button onClick={()=>addSection("hero")}>Add hero</button><button onClick={()=>addSection("richText")}>Add text</button><button onClick={()=>addSection("cta")}>Add button</button><button onClick={()=>addSection("cards")}>Add cards</button></div><button onClick={savePage}>Save page</button></>}</section>
 <section><h2>Publish</h2><p>Public URL: <Link href={`/sites/${site.slug}`}>/sites/{site.slug}</Link></p><button onClick={()=>setPreview(!preview)}>{preview?"Hide":"Show"} draft preview</button> <button onClick={publish}>Publish saved draft</button> {site.published_version&&site.published_version>1&&<button onClick={rollback}>Restore previous publication</button>}</section>
 {preview&&draft?.success&&<SiteView site={draft.data} pageSlug={current?.slug||"home"} preview/>}</>}
 <style jsx>{`.os-editor{padding:2rem;max-width:1200px;margin:auto;font-family:Arial,sans-serif}.os-editor section{border:1px solid #ccd5dc;border-radius:12px;padding:1.5rem;margin:1.5rem 0}.os-editor label{display:block;margin:.8rem 0}.os-editor input:not([type=color]):not([type=checkbox]),.os-editor select,.os-editor textarea{display:block;width:min(100%,600px);padding:.6rem;margin-top:.3rem}.os-editor button{padding:.7rem 1rem;margin:.3rem;background:#164e63;color:white;border:0;border-radius:6px;cursor:pointer}.os-section-editor{border-left:3px solid #0e7490;padding:1rem;margin:1rem 0}`}</style></main>
}
