import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BarChart3, ChevronRight, ClipboardCheck, Globe2, Medal, Users } from "lucide-react";
import { OmniTeamLogo } from "./omniteam-logo";

const modules = [
  { name: "OmniAthlete", category: "COMPLETE TEAM MANAGEMENT", description: "Manage swimmers, families, attendance, schedules, volunteers, and team communication in one integrated home.", icon: Users, artwork: "/images/modules/omniathlete.webp", active: true },
  { name: "OmniMeet", category: "HOSTED MEET SOFTWARE", description: "Online meet registration connected to standalone, downloadable meet software.", icon: Medal, artwork: "/images/modules/omnimeet.webp", active: true },
  { name: "OmniSite", category: "YOUR TEAM ONLINE", description: "Choose a template and build your team's website.", icon: Globe2, artwork: "/images/modules/omnisite.webp", active: true },
  { name: "OmniInsights", category: "TEAM ANALYTICS", description: "See membership, meet, volunteer, and financial trends.", icon: BarChart3, artwork: "/images/modules/omniinsights.webp" },
];

export default function Home() {
  return <main className="landing">
    <div className="landing-glow" aria-hidden="true" />
    <header className="landing-header">
      <Link href="/" aria-label="OmniTeam home"><OmniTeamLogo light /></Link>
      <div className="header-right"><span className="header-status"><span /> One platform. Every part of your team.</span><Link className="header-link" href="/dashboard">Team dashboard <ArrowRight size={16} /></Link></div>
    </header>
    <section className="landing-hero">
      <div className="hero-copy"><div className="hero-kicker"><span className="kicker-line" /> BUILT FOR THE WHOLE TEAM</div><h1>Everything your<br />team needs, <em>together.</em></h1><p>From the pool deck to meet day and everything in between, OmniTeam brings your people, plans, and progress into one connected home.</p><div className="hero-actions"><Link className="hero-cta" href="/subscribe">Start a team website <ArrowRight size={19} /></Link><a className="hero-secondary" href="#modules">Explore the platform <ChevronRight size={17} /></a></div></div>
      <div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="hero-art-core"><svg viewBox="0 0 64 64" fill="none"><path d="M32 5.5 55 18.75v26.5L32 58.5 9 45.25v-26.5L32 5.5Z" stroke="currentColor" strokeWidth="2"/><path d="M20 25.5 32 18l12 7.5v13L32 46l-12-7.5v-13Z" fill="currentColor"/><path d="M32 18v28M20 25.5l24 13M44 25.5 20 38.5" stroke="#102b32" strokeWidth="3"/></svg></div><span className="orbit-dot dot-a" /><span className="orbit-dot dot-b" /><span className="orbit-dot dot-c" /><span className="art-label label-one">ONE TEAM</span><span className="art-label label-two">EVERY MOMENT</span></div>
    </section>
    <section className="platform-section" id="modules"><div className="section-intro"><div><p className="section-kicker">THE OMNITEAM PLATFORM</p><h2>One home. Endless ways<br />to move forward.</h2></div><p>Explore four customer products supported by shared identity, security, subscriptions, and payments. OmniAthlete includes scheduling, volunteering, and communication.</p></div>
      <div className="modules-grid">{modules.map(({ name, category, description, icon: Icon, artwork, active }, index) => {
        const content = <><Image className="module-art" src={artwork} alt="" width={480} height={320} aria-hidden="true" /><div className="module-card-top"><span className="module-icon"><Icon size={23} strokeWidth={1.8} /></span><span className="module-number">{String(index + 1).padStart(2, "0")} / {String(modules.length).padStart(2, "0")}</span></div><div className="module-card-body"><span className="module-category">{category}</span><h3>{name}</h3><p>{description}</p></div><div className="module-footer"><span className={active ? "module-ready" : "module-soon"}>{active ? "In development" : "Planned"}</span><span className={active ? "module-arrow" : "module-arrow module-arrow-disabled"}><ArrowRight size={19} /></span></div></>;
        return active ? <Link className="module-card module-card-active" href={name === "OmniSite" ? "/omnisite" : name === "OmniMeet" ? "/omnimeet" : "/omniathlete"} key={name} aria-label={`Explore ${name}`}>{content}</Link> : <div className="module-card module-card-soon" key={name} aria-label={name + ", planned"}>{content}</div>;
      })}</div>
    </section>
    <section className="pricing-section" id="pricing"><div className="pricing-heading"><p className="section-kicker">CHOOSE THE WAY YOU WORK</p><h2>Three clear ways to use OmniTeam.</h2><p>Displayed prices are placeholders for the simulated flow. Payments are built into the workflows that need them and are never sold as a separate module.</p></div><div className="pricing-grid"><article><span>WEBSITE</span><h3>$29 <small>/ month</small></h3><p>Build and publish a branded team website, even if you use another system for team management.</p><ul><li>OmniSite</li><li>Templates, colors, and logo</li><li>No payment collected in testing</li></ul><Link href="/subscribe">Choose website <ArrowRight size={17}/></Link></article><article><span>TEAM MANAGEMENT</span><h3>$99 <small>/ month</small></h3><p>Run the team while keeping your existing website. Connect or link the systems as integration support grows.</p><ul><li>OmniAthlete team management</li><li>Scheduling, volunteers, and communication included</li><li>OmniInsights</li></ul><Link href="/subscribe">Choose management <ArrowRight size={17}/></Link></article><article className="pricing-featured"><span>COMPLETE TEAM</span><h3>$119 <small>/ month</small></h3><p>Combine the website and full team-management bundle in one connected account.</p><ul><li>Everything in Website</li><li>Everything in Team Management</li><li>Shared login and integrations</li></ul><Link href="/subscribe">Choose complete <ArrowRight size={17}/></Link></article></div><p className="meet-offer"><strong>Hosting a meet?</strong> OmniMeet connects online registration with standalone, downloadable meet software. <Link href="/omnimeet">Explore OmniMeet →</Link></p></section>
    <section className="landing-callout"><div className="callout-icon"><ClipboardCheck size={26} /></div><div><span>BUILDING OMNIATHLETE</span><h2>Start with your people.</h2><p>Explore family registration, team access, and attendance.</p></div><Link href="/omniathlete">Explore OmniAthlete <ArrowRight size={18} /></Link></section>
    <footer className="landing-footer"><OmniTeamLogo light compact /><span>Built for every team, every day.</span><span><Link href="/platform/login">Owner sign in</Link> · © {new Date().getFullYear()} OmniTeam</span></footer>
  </main>;
}
