"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { OMNITEAM_MODULES, type ModuleKey } from "@/lib/modules";
type Team={team_id:string;team_name:string;team_status:"ACTIVE"|"INACTIVE";is_test_team:boolean;created_at:string;plan_id:string|null;plan_name:string|null;subscription_status:string|null;billing_mode:string|null};
type TeamModule={team_id:string;module_key:ModuleKey;enabled:boolean};type Plan={id:string;name:string};
export default function PlatformConsole(){
 const router=useRouter();const client=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [teams,setTeams]=useState<Team[]>([]),[modules,setModules]=useState<TeamModule[]>([]),[plans,setPlans]=useState<Plan[]>([]),[teamName,setTeamName]=useState(""),[timezone,setTimezone]=useState("America/Los_Angeles"),[message,setMessage]=useState("Loading OmniTeam…"),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{if(!client)return;const [overview,moduleRows,planRows]=await Promise.all([client.rpc("list_platform_team_overview"),client.rpc("list_platform_team_modules"),client.from("subscription_plans").select("id,name").eq("active",true).order("display_order")]);const error=overview.error||moduleRows.error||planRows.error;if(error){setMessage(error.message);return}setTeams((overview.data??[]) as Team[]);setModules((moduleRows.data??[]) as TeamModule[]);setPlans((planRows.data??[]) as Plan[]);setMessage("")},[client]);
 useEffect(()=>{void load()},[load]);
 async function createTeam(event:FormEvent){event.preventDefault();if(!client)return;setBusy("create");const r=await client.rpc("create_platform_omnisite_team",{requested_team_name:teamName.trim(),requested_timezone:timezone});setMessage(r.error?.message||"Team created with OmniSite enabled.");if(!r.error){setTeamName("");await load()}setBusy("")}
 async function toggleModule(teamId:string,key:ModuleKey,enabled:boolean){if(!client)return;setBusy(`${teamId}:${key}`);const r=await client.rpc("platform_set_team_module",{target_team_id:teamId,target_module:key,enable_module:enabled});setMessage(r.error?.message||`${key} ${enabled?"enabled":"disabled"}.`);if(!r.error)await load();setBusy("")}
 async function setPlan(teamId:string,planId:string){if(!client||!planId)return;setBusy(`${teamId}:plan`);const r=await client.rpc("platform_set_team_plan",{target_team_id:teamId,target_plan_id:planId});setMessage(r.error?.message||"Mock plan and module entitlements updated.");if(!r.error)await load();setBusy("")}
 async function setStatus(team:Team){if(!client)return;setBusy(`${team.team_id}:status`);const activating=team.team_status!=="ACTIVE";const r=await client.rpc("platform_set_team_status",{target_team_id:team.team_id,activate:activating});setMessage(r.error?.message||`Team ${activating?"reactivated":"archived"}.`);if(!r.error)await load();setBusy("")}
 async function signOut(){if(client)await client.auth.signOut();router.replace("/platform/login");router.refresh()}
 const active=teams.filter(t=>t.team_status==="ACTIVE").length,sites=modules.filter(m=>m.module_key==="omnisite"&&m.enabled).length,trials=teams.filter(t=>t.subscription_status==="TRIALING").length;
 return <main className="owner-dashboard"><aside><Link href="/" className="registration-brand">Omni<span>Team</span></Link><p>OWNER CONTROL</p><nav><a href="#overview">Overview</a><a href="#teams">Teams</a><Link href="/omnisite/templates">Templates</Link><Link href="/platform/support">Support access</Link><Link href="/developer/api">Admin API</Link></nav><button onClick={signOut}>Sign out</button></aside><div className="owner-main"><header><div><p className="registration-kicker">OMNITEAM OWNER</p><h1>Platform dashboard</h1></div><Link href="/subscribe">View client subscription flow</Link></header>{message&&<p className="registration-message" role="status">{message}</p>}
 <section id="overview" className="owner-stats"><article><span>Total teams</span><strong>{teams.length}</strong></article><article><span>Active teams</span><strong>{active}</strong></article><article><span>OmniSite teams</span><strong>{sites}</strong></article><article><span>Mock trials</span><strong>{trials}</strong></article></section>
 <section className="owner-panel"><h2>Create a team directly</h2><p>For testing or support setup. The public client flow is available under Subscriptions.</p><form className="platform-team-form" onSubmit={createTeam}><label>Team name<input required minLength={2} maxLength={120} value={teamName} onChange={e=>setTeamName(e.target.value)}/></label><label>Timezone<select value={timezone} onChange={e=>setTimezone(e.target.value)}><option>America/Los_Angeles</option><option>America/Denver</option><option>America/Chicago</option><option>America/New_York</option></select></label><button disabled={busy==="create"}>{busy==="create"?"Creating…":"Create OmniSite team"}</button></form></section>
 <section id="teams" className="owner-panel"><div className="owner-panel-heading"><div><h2>Teams and subscriptions</h2><p>Plan changes reset entitlements to that plan. Individual switches are audited owner overrides.</p></div></div>{teams.length===0?<p>No teams yet.</p>:<div className="owner-team-list">{teams.map(team=><article key={team.team_id}><div className="owner-team-heading"><div><h3>{team.team_name}</h3><p>{team.team_status} · {team.is_test_team?"Test team":"Non-test team"} · {team.plan_name??"Direct provisioning"} {team.subscription_status&&`· ${team.subscription_status}`}</p><small>{team.team_id}</small></div><button onClick={()=>setStatus(team)} disabled={busy===`${team.team_id}:status`}>{team.team_status==="ACTIVE"?"Archive":"Reactivate"}</button></div><div className="owner-plan"><label>Mock subscription plan<select defaultValue="" onChange={e=>void setPlan(team.team_id,e.target.value)}><option value="">Choose plan…</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label></div><div className="owner-module-switches">{OMNITEAM_MODULES.map(module=>{const enabled=modules.some(m=>m.team_id===team.team_id&&m.module_key===module.key&&m.enabled);return <label key={module.key}><input type="checkbox" checked={enabled} disabled={busy===`${team.team_id}:${module.key}`} onChange={e=>void toggleModule(team.team_id,module.key,e.target.checked)}/><span>{module.name}</span></label>})}</div><div className="owner-team-links"><Link href="/dashboard">Team dashboard</Link>{modules.some(m=>m.team_id===team.team_id&&m.module_key==="omnisite"&&m.enabled)&&<Link href="/omnisite">OmniSite builder</Link>}</div></article>)}</div>}</section></div></main>
}
