"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { authCallbackUrl } from "@/lib/site-url";

type Plan={id:string;name:string;description:string;monthly_price_cents:number;module_keys:string[]};
type Stage="account"|"plan"|"review"|"complete";
export default function SubscribePage(){
 const router=useRouter();
 const client=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [plans,setPlans]=useState<Plan[]>([]),[planId,setPlanId]=useState(""),[stage,setStage]=useState<Stage>("account"),[mode,setMode]=useState<"signup"|"signin">("signup");
 const [firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [teamName,setTeamName]=useState(""),[timezone,setTimezone]=useState("America/Los_Angeles"),[checkoutId,setCheckoutId]=useState("");
 const [message,setMessage]=useState("Create an account or sign in to start."),[busy,setBusy]=useState(false);
 useEffect(()=>{async function init(){if(!client){setMessage("Supabase is not configured.");return}const [auth,planResult]=await Promise.all([client.auth.getUser(),client.from("subscription_plans").select("id,name,description,monthly_price_cents,module_keys").eq("active",true).order("display_order")]);if(planResult.error){setMessage(planResult.error.message);return}const list=(planResult.data??[]) as Plan[];setPlans(list);setPlanId(list[0]?.id||"");if(auth.data.user){setStage("plan");setMessage("Choose a plan and name your team.")}}void init()},[client]);
 async function authenticate(event:FormEvent){event.preventDefault();if(!client)return;setBusy(true);if(mode==="signup"){const r=await client.auth.signUp({email:email.trim(),password,options:{data:{first_name:firstName.trim(),last_name:lastName.trim()},emailRedirectTo:authCallbackUrl("/subscribe")}});if(r.error)setMessage(r.error.message);else if(!r.data.session)setMessage("Check your email to confirm the account, then return and sign in.");else{setStage("plan");setMessage("Choose a plan and name your team.")}}else{const r=await client.auth.signInWithPassword({email:email.trim(),password});if(r.error)setMessage(r.error.message);else{setStage("plan");setMessage("Choose a plan and name your team.")}}setBusy(false)}
 async function begin(event:FormEvent){event.preventDefault();if(!client)return;setBusy(true);const r=await client.rpc("begin_mock_checkout",{selected_plan_id:planId,requested_team_name:teamName.trim(),requested_timezone:timezone});if(r.error)setMessage(r.error.message);else{setCheckoutId(r.data as string);setStage("review");setMessage("Review the simulated order. No card will be charged.")}setBusy(false)}
 async function complete(){if(!client||!checkoutId)return;setBusy(true);const r=await client.rpc("complete_mock_checkout",{target_checkout_id:checkoutId});if(r.error){setMessage(r.error.message);setBusy(false);return}setStage("complete");setMessage("Your mock subscription is active and the team is ready.");setBusy(false)}
 const selected=plans.find(p=>p.id===planId);
 return <main className="subscribe-page"><div className="subscribe-wrap"><Link href="/" className="registration-brand">Omni<span>Team</span></Link><p className="registration-kicker">START YOUR TEAM</p><h1>Build your team website</h1><ol className="subscribe-steps"><li className={stage==="account"?"active":""}>Account</li><li className={stage==="plan"?"active":""}>Plan</li><li className={stage==="review"?"active":""}>Review</li><li className={stage==="complete"?"active":""}>Ready</li></ol>
 {stage==="account"&&<section className="subscribe-card"><h2>{mode==="signup"?"Create your account":"Sign in"}</h2><form onSubmit={authenticate}>{mode==="signup"&&<div className="registration-row"><label>First name<input required value={firstName} onChange={e=>setFirstName(e.target.value)}/></label><label>Last name<input required value={lastName} onChange={e=>setLastName(e.target.value)}/></label></div>}<label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={8} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create account":"Sign in"}</button></form><button className="subscribe-link" onClick={()=>setMode(mode==="signup"?"signin":"signup")}>{mode==="signup"?"I already have an account":"Create a new account"}</button></section>}
 {stage==="plan"&&<section className="subscribe-card"><h2>Choose your plan</h2><div className="plan-grid">{plans.map(plan=><button key={plan.id} className={planId===plan.id?"plan selected":"plan"} onClick={()=>setPlanId(plan.id)}><strong>{plan.name}</strong><span>${(plan.monthly_price_cents/100).toFixed(0)} / month</span><p>{plan.description}</p><small>{plan.module_keys.join(" + ")}</small></button>)}</div><form onSubmit={begin}><label>Team name<input required minLength={2} maxLength={120} value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder="Example Swim Club"/></label><label>Timezone<select value={timezone} onChange={e=>setTimezone(e.target.value)}><option>America/Los_Angeles</option><option>America/Denver</option><option>America/Chicago</option><option>America/New_York</option><option>Pacific/Honolulu</option><option>America/Anchorage</option></select></label><button disabled={busy||!planId}>{busy?"Preparing…":"Continue to review"}</button></form></section>}
 {stage==="review"&&selected&&<section className="subscribe-card"><h2>Review subscription</h2><dl className="order-summary"><div><dt>Team</dt><dd>{teamName}</dd></div><div><dt>Plan</dt><dd>{selected.name}</dd></div><div><dt>Displayed price</dt><dd>${(selected.monthly_price_cents/100).toFixed(2)} / month</dd></div><div><dt>Payment today</dt><dd>$0.00</dd></div></dl><p className="mock-notice">Simulation only. Completing this step creates the team and a 30-day mock trial. No payment information is collected.</p><button onClick={complete} disabled={busy}>{busy?"Creating team…":"Start mock subscription"}</button></section>}
 {stage==="complete"&&<section className="subscribe-card"><h2>Your team is ready</h2><p>You are the team owner. Your subscribed modules are now available on the team dashboard.</p><button onClick={()=>router.push("/dashboard")}>Open team dashboard</button></section>}
 <p className="registration-message" role="status">{message}</p></div></main>
}
