"use client";
import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import Link from "next/link";
import { DEFAULT_THEME, pageSchema, snapshotSchema, themeSchema, type SitePage, type SiteTheme } from "@/modules/omnisite/model";
import { SiteView } from "@/modules/omnisite/SiteView";
type Template={id:string;name:string;layout_key:"classic"|"bold"|"minimal";status:"DRAFT"|"PUBLISHED"|"RETIRED";starter_pages:SitePage[];default_theme:SiteTheme;version:number};
export default function TemplateManager(){
 const client=useMemo(()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return u&&k?createBrowserClient(u,k):null},[]);
 const [list,setList]=useState<Template[]>([]),[selected,setSelected]=useState<Template|null>(null),[message,setMessage]=useState("Sign in with your OmniTeam platform-owner account."),[preview,setPreview]=useState(false);
 async function refresh(){if(!client)return;const r=await client.from("site_templates").select("*").order("created_at");if(r.error){setMessage(r.error.message);return}setList((r.data??[]) as Template[]);setMessage("")}
 useEffect(()=>{async function init(){if(!client)return;const a=await client.auth.getUser();if(!a.data.user)return;const r=await client.rpc("is_platform_owner");if(r.error||!r.data){setMessage("Platform-owner access required.");return}await refresh()}void init()},[client]);
 async function save(){if(!client||!selected)return;const theme=themeSchema.safeParse(selected.default_theme);const pages=selected.starter_pages.map(p=>pageSchema.safeParse(p));if(!theme.success||pages.some(p=>!p.success)||!selected.name.trim()){setMessage("Fix template name, colors, page content, or links.");return}const row={name:selected.name.trim(),layout_key:selected.layout_key,starter_pages:pages.map(p=>p.data),default_theme:theme.data,status:selected.status,version:selected.version+1,updated_at:new Date().toISOString()};const r=selected.id?await client.from("site_templates").update(row).eq("id",selected.id):await client.from("site_templates").insert({...row,status:"DRAFT",version:1});setMessage(r.error?.message||"Template saved.");if(!r.error)await refresh()}
 async function changeStatus(status:Template["status"]){if(!client||!selected?.id)return;const r=await client.from("site_templates").update({status,updated_at:new Date().toISOString()}).eq("id",selected.id);setMessage(r.error?.message||`Template ${status.toLowerCase()}.`);if(!r.error){setSelected({...selected,status});await refresh()}}
 function duplicate(){if(!selected)return;setSelected({...selected,id:"",name:`${selected.name} copy`,status:"DRAFT",version:0})}
 const sample=selected?snapshotSchema.safeParse({schemaVersion:1,teamId:"00000000-0000-4000-8000-000000000001",siteId:"00000000-0000-4000-8000-000000000002",slug:"preview",siteName:selected.name,layout:selected.layout_key,theme:selected.default_theme,logoPath:null,pages:selected.starter_pages}):null;
 return <main className="os-editor"><Link href="/">← OmniTeam</Link><h1>OmniSite template catalog</h1><p role="status">{message}</p>{list.length>0&&<><label>Template <select value={selected?.id||""} onChange={e=>setSelected(list.find(t=>t.id===e.target.value)||null)}><option value="">Select</option>{list.map(t=><option key={t.id} value={t.id}>{t.name} ({t.status})</option>)}</select></label><button onClick={()=>setSelected({id:"",name:"New team template",layout_key:"classic",status:"DRAFT",starter_pages:list[0]?.starter_pages||[],default_theme:DEFAULT_THEME,version:0})}>New template</button> <button disabled={!selected} onClick={duplicate}>Duplicate</button></>}
 {selected&&<section><label>Name <input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Layout <select value={selected.layout_key} onChange={e=>setSelected({...selected,layout_key:e.target.value as Template["layout_key"]})}><option value="classic">Classic</option><option value="bold">Bold</option><option value="minimal">Minimal</option></select></label>{(["primary","secondary","accent"] as const).map(k=><label key={k}>{k} <input type="color" value={selected.default_theme[k]} onChange={e=>setSelected({...selected,default_theme:{...selected.default_theme,[k]:e.target.value}})}/></label>)}<p>Starter pages: {selected.starter_pages.map(p=>p.title).join(", ")}</p><label>Starter pages JSON<textarea rows={16} value={JSON.stringify(selected.starter_pages,null,2)} onChange={e=>{try{setSelected({...selected,starter_pages:JSON.parse(e.target.value)})}catch{setMessage("Starter pages JSON is invalid.")}}}/></label><button onClick={save}>Save template</button>{selected.id&&<><button onClick={()=>changeStatus("PUBLISHED")}>Publish</button><button onClick={()=>changeStatus("RETIRED")}>Retire</button></>}<button onClick={()=>setPreview(!preview)}>Preview</button></section>}
 {preview&&sample?.success&&<SiteView site={sample.data} preview/>}
 <style jsx>{`.os-editor{padding:2rem;max-width:1200px;margin:auto;font-family:Arial,sans-serif}.os-editor section{border:1px solid #ccd5dc;border-radius:12px;padding:1.5rem;margin:1.5rem 0}.os-editor label{display:block;margin:.8rem 0}.os-editor input:not([type=color]),.os-editor select,.os-editor textarea{display:block;width:min(100%,700px);padding:.6rem;margin-top:.3rem}.os-editor button{padding:.7rem 1rem;margin:.3rem;background:#164e63;color:white;border:0;border-radius:6px;cursor:pointer}`}</style></main>
}
